Added DevEnvironment context and donwload links
OMNIALowCode/omnia3 pull request #71
Opened 2020-09-22 11:14 UTC by zebilha

2020-09-23 10:32 UTC, daniel8lopes approved these changes

2020-11-12 15:51 UTC, gsferreira requested changes

2020-11-12 15:51 UTC, gsferreira commented on docs/pages/omnia3/Downloads/omnia3_feed.md
> +OMNIA Platform is composed of three different resources that you can download and install: Platform, Connector and Docker.
Development Environment

2020-11-12 15:51 UTC, gsferreira commented on docs/pages/omnia3/Downloads/omnia3_feed.md
> +These resources are available online to be downloaded. A feed, in the form of a xml file, is available to simplify the download of the Platform, Connector and Docker versions.
Development Environment

2020-11-12 15:51 UTC, gsferreira commented on docs/pages/omnia3/Modeler/omnia3_modeler_developingbehaviours.md
> +## 7. Development Environment (Docker)
I think we can remove the reference to docker from the title

2020-11-12 15:51 UTC, gsferreira commented on docs/pages/omnia3/Modeler/omnia3_modeler_developingbehaviours.md
> +To develop an OMNIA Platform on top of a Docker you will need to:
To develop an OMNIA Platform on ~~top of a Docker~~ on your local machine  you will need to:

2020-11-12 15:51 UTC, gsferreira commented on docs/pages/omnia3/Modeler/omnia3_modeler_developingbehaviours.md
> +- Install Docker. [Click here to download](https://www.docker.com/products/docker-desktop/);
Any version recommended?

2020-11-12 15:51 UTC, gsferreira commented on docs/pages/omnia3/Modeler/omnia3_modeler_developingbehaviours.md
> +A new tab on your browser should open in `http://host.docker.internal:5000`, providing you the full OMNIA experience right from machine.
"When the development is ready, a new tab will be automatically open..."

2020-11-12 15:51 UTC, gsferreira commented on docs/pages/omnia3/Modeler/omnia3_modeler_developingbehaviours.md
> +### 7.7. Useful Docker commands
I think we can rename this section to something like "Managing your development environment"

2020-11-12 15:57 UTC, DiogoTx commented on docs/js/customscripts.js
> +      'Download latest docker version',
Development Environment instead of Docker

2020-11-13 12:59 UTC, DiogoTx commented on docs/pages/omnia3/Modeler/omnia3_modeler_developingbehaviours.md
> +- Install Docker. [Click here to download](https://www.docker.com/products/docker-desktop/);
Reviewed on file omnia3_environmentsetup

2020-11-13 13:02 UTC, DiogoTx commented on docs/pages/omnia3/Modeler/omnia3_modeler_developingbehaviours.md
> +A new tab on your browser should open in `http://host.docker.internal:5000`, providing you the full OMNIA experience right from machine.
Reviewed on file omnia3_environmentsetup

2020-11-13 14:46 UTC, gsferreira requested changes

2020-11-13 14:46 UTC, gsferreira commented on docs/pages/omnia3/GettingStarted/omnia3_clisetup.md
> +toc: false
We should use give also examples in the context of the dev environement

2020-11-13 14:46 UTC, gsferreira commented on docs/pages/omnia3/GettingStarted/omnia3_connectordevelopment.md
> +- Sync model changes using Omnia-CLI
How?

2020-11-13 14:46 UTC, gsferreira commented on docs/pages/omnia3/GettingStarted/omnia3_connectordevelopment.md
> +- After changing the behaviours code, use Visual Studio *Debug* to test your changes
How?

2020-11-13 14:46 UTC, gsferreira commented on docs/pages/omnia3/GettingStarted/omnia3_connectordevelopment.md
> +- Sync model changes using Omnia-CLI
Use something like "When you are happy with the code, sync model changes using Omnia CLI"

2020-11-13 14:46 UTC, gsferreira commented on docs/pages/omnia3/GettingStarted/omnia3_databasedevelopment.md
> +To access your subscription Database, you first need to instantiate pgAdmin. For that, in Docker expand _Containers_ and check the "`PORT`" number where the "`omniaplatform_pgadmin`" container is run
use the docker dns instead of localhost

2020-11-13 14:46 UTC, gsferreira commented on docs/pages/omnia3/GettingStarted/omnia3_databasedevelopment.md
> +- Set the "`PORT`" of the _Container_ "`omniaplatform_database`" (check it in Docker, like you did before for "`omniaplatform_pgadmin`") as _Port_;
What is the default port?

2020-11-13 14:46 UTC, gsferreira commented on docs/pages/omnia3/GettingStarted/omnia3_environmentsetup.md
> +- [Download](omnia3_downloads.html) development package
development environment package

2020-11-13 14:46 UTC, gsferreira commented on docs/pages/omnia3/Modeler/omnia3_modeler_developmentenvironment.md
> +OMNIA Development Environment run in containers using Docker, allowing the user to manage it's instances using the `docker-compose` PowerShell commands.
How to see logs?

2020-11-13 14:46 UTC, gsferreira commented on docs/pages/omnia3/GettingStarted/omnia3_environmentsetup.md
> +| **pgAdmin (database client)** | http://localhost:16543 |
can I use host.docker.internal?

2020-11-13 14:46 UTC, gsferreira commented on docs/pages/omnia3/Modeler/omnia3_modeler_developmentenvironment.md
> +## 1. Introduction
How to install a specific version?

2020-11-13 14:46 UTC, gsferreira commented on docs/pages/omnia3/GettingStarted/omnia3_modeldeployment.md
> +Download model behaviours to a local environment using the following command:
Can't I use the portal to do that?

2020-11-13 14:46 UTC, gsferreira commented on docs/pages/omnia3/GettingStarted/omnia3_serverdevelopment.md
> +A new Visual Studio Code window will now open. In the project file Explorer, navigate to "`/Behaviours`" folder, double click the "`dev.code-workspace`" file to open the Server development workspace.
"In the project file Explorer, navigate to "`/Behaviours`" folder, double click the "`dev.code-workspace`" file to open the Server development workspace." -> Do I really need to do that?

2020-11-13 14:46 UTC, gsferreira commented on docs/pages/omnia3/GettingStarted/omnia3_serverdevelopment.md
> +omnia-cli model behaviours apply --subscription [Subscription] --tenant [Tenant] --environment [Environment] --path [Path] --build
Please give a real world example also.
I also would like to know that subscription may not be required or even the Path.

2020-11-13 14:46 UTC, gsferreira commented on docs/pages/omnia3/GettingStarted/omnia3_serverdevelopment.md
> +## 3. Change code and apply changes to Model
It's important to be clear that this replaces all the code in the model.

2020-11-13 14:46 UTC, gsferreira commented on docs/pages/omnia3/GettingStarted/omnia3_serverdevelopment.md
> +Another notification to restore code dependencies must also prompts in the first time running the workspace, having you to confirm it to avoid errors.
Explain that this is required even after a Clean & Build

2020-11-13 14:46 UTC, gsferreira commented on docs/pages/omnia3/GettingStarted/omnia3_uidevelopment.md
> +When you're satisfied with the result, you can apply the code to the Tenant's model using OMNIA CLI. For that, run the following code line in Powershell:
Do we support that?

2020-11-13 14:51 UTC, zebilha commented on docs/pages/omnia3/GettingStarted/omnia3_databasedevelopment.md
> +- Set the "`PORT`" of the _Container_ "`omniaplatform_database`" (check it in Docker, like you did before for "`omniaplatform_pgadmin`") as _Port_;
16543. Should I add a more advanced explanation below on how to get port if it fails to connect?

2020-11-13 14:59 UTC, zebilha commented on docs/pages/omnia3/Modeler/omnia3_modeler_developmentenvironment.md
> +OMNIA Development Environment run in containers using Docker, allowing the user to manage it's instances using the `docker-compose` PowerShell commands.
Great!
I'll add a 4rd topic on _'Access to OMNIA Platform Logs'_. I'll also explain what each container log, but should I include all containers or just a few?

2020-11-13 15:01 UTC, DiogoTx commented on docs/pages/omnia3/GettingStarted/omnia3_connectordevelopment.md
> +- Sync model changes using Omnia-CLI
Added link to CLI model download documentation

2020-11-13 15:01 UTC, DiogoTx commented on docs/pages/omnia3/GettingStarted/omnia3_connectordevelopment.md
> +- After changing the behaviours code, use Visual Studio *Debug* to test your changes
Added link to CLI model update documentation

2020-11-13 15:01 UTC, DiogoTx commented on docs/pages/omnia3/GettingStarted/omnia3_connectordevelopment.md
> +- Sync model changes using Omnia-CLI
Review text according to suggestion

2020-11-13 15:04 UTC, gsferreira commented on docs/pages/omnia3/GettingStarted/omnia3_databasedevelopment.md
> +- Set the "`PORT`" of the _Container_ "`omniaplatform_database`" (check it in Docker, like you did before for "`omniaplatform_pgadmin`") as _Port_;
I think we should write based on the default scenario. And explain how to find the port (that would be useful if the process was customized).

2020-11-13 15:05 UTC, gsferreira commented on docs/pages/omnia3/Modeler/omnia3_modeler_developmentenvironment.md
> +OMNIA Development Environment run in containers using Docker, allowing the user to manage it's instances using the `docker-compose` PowerShell commands.
Explaining how to access the dashboard should be enough.
Besides that we can explain where the log files are stored inside the containers

2020-11-13 15:11 UTC, DiogoTx commented on docs/pages/omnia3/GettingStarted/omnia3_environmentsetup.md
> +| **pgAdmin (database client)** | http://localhost:16543 |
Reviewed

2020-11-13 15:11 UTC, DiogoTx commented on docs/pages/omnia3/GettingStarted/omnia3_environmentsetup.md
> +- [Download](omnia3_downloads.html) development package
Reviewed

2020-11-13 15:34 UTC, DiogoTx commented on docs/pages/omnia3/GettingStarted/omnia3_clisetup.md
> +toc: false
Added Cli examples

2020-11-13 15:45 UTC, DiogoTx commented on docs/pages/omnia3/GettingStarted/omnia3_modeldeployment.md
> +Download model behaviours to a local environment using the following command:
Added portal options for model import/export

2020-11-16 12:00 UTC, gsferreira approved these changes

2020-11-16 14:55 UTC, daniel8lopes approved these changes

2020-11-16 23:03 UTC, merged