Rename behaviour methods
OMNIALowCode/omnia3 pull request #74
Opened 2020-11-12 17:45 UTC by gsferreira

2020-11-13 14:30 UTC, zebilha commented on docs/pages/omnia3/Modeler/omnia3_modeler_bestpractices.md
> +When working with c# Tasks using ".GetAwaiter().GetResult()", ".Result" or ".Wait()" to get the result cam cause [deadlocks or thread pool starvation](https://gsferreira.com/archive/2020/08/avoid-get
to get the result **can** cause

2020-11-13 14:39 UTC, zebilha requested changes

2020-11-13 14:39 UTC, zebilha commented on docs/pages/omnia3/Modeler/omnia3_modeler_bestpractices.md
> +When working with c# Tasks using ".GetAwaiter().GetResult()", ".Result" or ".Wait()" to get the result cam cause [deadlocks or thread pool starvation](https://gsferreira.com/archive/2020/08/avoid-get
to get the result **cam** cause

2020-11-13 15:06 UTC, zebilha approved these changes

2020-11-16 11:35 UTC, daniel8lopes approved these changes

2020-11-16 11:37 UTC, daniel8lopes commented on docs/pages/omnia3/Modeler/omnia3_modeler_bestpractices.md
> +In cases like Initialize behaviours or Action/Change behaviours, you can't use async/await. On those cases, you should extract async methods to Code Dependencies and use "GetAwaiter().GetResult()" ju
In cases like Initialize behaviours or Action/Change behaviours, you can't use async/await. In these cases, you should extract async methods to Code Dependencies and use "GetAwaiter().GetResult()" just once to wait for that Code Dependency.

2020-11-16 11:38 UTC, daniel8lopes reviewed
Commented correction

2020-11-16 11:39 UTC, daniel8lopes approved these changes

2020-11-16 11:39 UTC, daniel8lopes approved these changes

2020-11-16 23:05 UTC, merged